---
editor: source
---

# Installation

Dieses Skript wird als Standardvorlage auf Posit Cloud verwendet, um die erforderlichen R Pakete zu installieren, die zur Durchführung des Kurses benötigt werden.

```{r}

install.packages(c("devtools", 
                   "usethis", 
                   "knitr", 
                   "tidyverse", 
                   "ggthemes", 
                   "palmerpenguins",
                   "gt",
                   "here",
                   "gapminder",
                   "ggthemes",
                   "ggridges",
                   "sf",
                   "rnaturalearth",
                   "readxl",
                   "janitor",
                   "googlesheets4",
                   "nycflights13",
                   "DT",
                   "gt",
                   "quarto"))
```

```{r}
library(devtools)
library(usethis)
library(tidyverse)
library(ggthemes)
library(palmerpenguins)
library(gt)
library(here)
library(gapminder)
library(ggthemes)
library(ggridges)
library(sf)
library(rnaturalearth)
library(readxl)
library(readr)
library(janitor)
library(googlesheets4)
library(DT)
library(gt)
```


